---
version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: dkrmm
    container_name: api
    environment:
      - PRODUCTION=False
    networks:
      - net
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - cache
      - db
    restart: always
  cache:
    image: redis:7-alpine
    container_name: cache
    networks:
      - net
    ports:
      - "6379:6379"
    restart: always
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$DKRMM_POSTGRES_PASSWORD
      - POSTGRES_DB=postgres
    networks:
      - net
    volumes:
      - postgres-data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
networks:
  net:
volumes:
  postgres-data:
